/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  admins: () => import("@/views/admins/index.vue"),
  agents: () => import("@/views/agents/index.vue"),
  "ai-resources_accounts": () => import("@/views/ai-resources/accounts/index.vue"),
  "ai-resources_channels": () => import("@/views/ai-resources/channels/index.vue"),
  "ai-resources_groups": () => import("@/views/ai-resources/groups/index.vue"),
  "ai-resources_monitoring": () => import("@/views/ai-resources/monitoring/index.vue"),
  "ai-resources_network": () => import("@/views/ai-resources/network/index.vue"),
  "ai-resources_proxies": () => import("@/views/ai-resources/proxies/index.vue"),
  announcements: () => import("@/views/announcements/index.vue"),
  audit: () => import("@/views/audit/index.vue"),
  billing_orders: () => import("@/views/billing/orders/index.vue"),
  billing_overview: () => import("@/views/billing/overview/index.vue"),
  billing_plans: () => import("@/views/billing/plans/index.vue"),
  billing_providers: () => import("@/views/billing/providers/index.vue"),
  billing_subscriptions: () => import("@/views/billing/subscriptions/index.vue"),
  categories: () => import("@/views/categories/index.vue"),
  home: () => import("@/views/home/index.vue"),
  marketing: () => import("@/views/marketing/index.vue"),
  media: () => import("@/views/media/index.vue"),
  operations_alerts: () => import("@/views/operations/alerts/index.vue"),
  operations_diagnostics: () => import("@/views/operations/diagnostics/index.vue"),
  operations_overview: () => import("@/views/operations/overview/index.vue"),
  operations_traffic: () => import("@/views/operations/traffic/index.vue"),
  "operations_usage-logs": () => import("@/views/operations/usage-logs/index.vue"),
  pets: () => import("@/views/pets/index.vue"),
  plugins: () => import("@/views/plugins/index.vue"),
  publishing: () => import("@/views/publishing/index.vue"),
  runtime_commands: () => import("@/views/runtime/commands/index.vue"),
  runtime_events: () => import("@/views/runtime/events/index.vue"),
  runtime_instances: () => import("@/views/runtime/instances/index.vue"),
  runtime_operations: () => import("@/views/runtime/operations/index.vue"),
  runtime_releases: () => import("@/views/runtime/releases/index.vue"),
  security_account: () => import("@/views/security/account/index.vue"),
  security_risk: () => import("@/views/security/risk/index.vue"),
  skills: () => import("@/views/skills/index.vue"),
  system_data: () => import("@/views/system/data/index.vue"),
  system_settings: () => import("@/views/system/settings/index.vue"),
  users: () => import("@/views/users/index.vue"),
};
