/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'admins',
    path: '/admins',
    component: 'layout.base$view.admins',
    meta: {
      title: 'admins',
      i18nKey: 'route.admins',
      capability: 'admins:read',
      icon: 'mdi:shield-account-outline',
      order: 90
    }
  },
  {
    name: 'agents',
    path: '/agents',
    component: 'layout.base$view.agents',
    meta: {
      title: 'agents',
      i18nKey: 'route.agents',
      capability: 'content:agents:read',
      icon: 'mdi:robot-outline',
      order: 10
    }
  },
  {
    name: 'ai-resources',
    path: '/ai-resources',
    component: 'layout.base',
    meta: {
      title: 'ai-resources',
      i18nKey: 'route.ai-resources',
      capability: 'ai-resources:read',
      icon: 'mdi:server-network-outline',
      order: 21
    },
    children: [
      {
        name: 'ai-resources_accounts',
        path: '/ai-resources/accounts',
        component: 'view.ai-resources_accounts',
        meta: {
          title: 'ai-resources_accounts',
          i18nKey: 'route.ai-resources_accounts',
          capability: 'ai-resources:read'
        }
      },
      {
        name: 'ai-resources_channels',
        path: '/ai-resources/channels',
        component: 'view.ai-resources_channels',
        meta: {
          title: 'ai-resources_channels',
          i18nKey: 'route.ai-resources_channels',
          capability: 'ai-resources:read'
        }
      },
      {
        name: 'ai-resources_groups',
        path: '/ai-resources/groups',
        component: 'view.ai-resources_groups',
        meta: {
          title: 'ai-resources_groups',
          i18nKey: 'route.ai-resources_groups',
          capability: 'ai-resources:read'
        }
      },
      {
        name: 'ai-resources_monitoring',
        path: '/ai-resources/monitoring',
        component: 'view.ai-resources_monitoring',
        meta: {
          title: 'ai-resources_monitoring',
          i18nKey: 'route.ai-resources_monitoring',
          capability: 'ai-resources:read'
        }
      },
      {
        name: 'ai-resources_network',
        path: '/ai-resources/network',
        component: 'view.ai-resources_network',
        meta: {
          title: 'ai-resources_network',
          i18nKey: 'route.ai-resources_network',
          capability: 'ai-resources:read'
        }
      },
      {
        name: 'ai-resources_proxies',
        path: '/ai-resources/proxies',
        component: 'view.ai-resources_proxies',
        meta: {
          title: 'ai-resources_proxies',
          i18nKey: 'route.ai-resources_proxies',
          capability: 'ai-resources:read'
        }
      }
    ]
  },
  {
    name: 'announcements',
    path: '/announcements',
    component: 'layout.base$view.announcements',
    meta: {
      title: 'announcements',
      i18nKey: 'route.announcements',
      capability: 'operations:read',
      icon: 'mdi:bullhorn-outline',
      order: 37
    }
  },
  {
    name: 'audit',
    path: '/audit',
    component: 'layout.base$view.audit',
    meta: {
      title: 'audit',
      i18nKey: 'route.audit',
      capability: 'audit:read',
      icon: 'mdi:history',
      order: 70
    }
  },
  {
    name: 'billing',
    path: '/billing',
    component: 'layout.base',
    meta: {
      title: 'billing',
      i18nKey: 'route.billing',
      capability: 'billing:read',
      icon: 'mdi:credit-card-outline',
      order: 30
    },
    children: [
      {
        name: 'billing_orders',
        path: '/billing/orders',
        component: 'view.billing_orders',
        meta: {
          title: 'billing_orders',
          i18nKey: 'route.billing_orders',
          capability: 'billing:read'
        }
      },
      {
        name: 'billing_overview',
        path: '/billing/overview',
        component: 'view.billing_overview',
        meta: {
          title: 'billing_overview',
          i18nKey: 'route.billing_overview',
          capability: 'billing:read'
        }
      },
      {
        name: 'billing_plans',
        path: '/billing/plans',
        component: 'view.billing_plans',
        meta: {
          title: 'billing_plans',
          i18nKey: 'route.billing_plans',
          capability: 'billing:read'
        }
      },
      {
        name: 'billing_providers',
        path: '/billing/providers',
        component: 'view.billing_providers',
        meta: {
          title: 'billing_providers',
          i18nKey: 'route.billing_providers',
          capability: 'billing:read'
        }
      },
      {
        name: 'billing_subscriptions',
        path: '/billing/subscriptions',
        component: 'view.billing_subscriptions',
        meta: {
          title: 'billing_subscriptions',
          i18nKey: 'route.billing_subscriptions',
          capability: 'billing:read'
        }
      }
    ]
  },
  {
    name: 'categories',
    path: '/categories',
    component: 'layout.base$view.categories',
    meta: {
      title: 'categories',
      i18nKey: 'route.categories',
      icon: 'material-symbols:folder-outline',
      capability: 'content:categories:read',
      order: 11
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      capability: 'dashboard:read'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'marketing',
    path: '/marketing',
    component: 'layout.base$view.marketing',
    meta: {
      title: 'marketing',
      i18nKey: 'route.marketing',
      capability: 'billing:read',
      icon: 'mdi:ticket-percent-outline',
      order: 36
    }
  },
  {
    name: 'media',
    path: '/media',
    component: 'layout.base$view.media',
    meta: {
      title: 'media',
      i18nKey: 'route.media',
      capability: 'content:media:read',
      icon: 'mdi:image-multiple-outline',
      order: 14
    }
  },
  {
    name: 'operations',
    path: '/operations',
    component: 'layout.base',
    meta: {
      title: 'operations',
      i18nKey: 'route.operations',
      capability: 'operations:read',
      icon: 'mdi:chart-timeline-variant',
      order: 40
    },
    children: [
      {
        name: 'operations_alerts',
        path: '/operations/alerts',
        component: 'view.operations_alerts',
        meta: {
          title: 'operations_alerts',
          i18nKey: 'route.operations_alerts',
          capability: 'operations:read'
        }
      },
      {
        name: 'operations_diagnostics',
        path: '/operations/diagnostics',
        component: 'view.operations_diagnostics',
        meta: {
          title: 'operations_diagnostics',
          i18nKey: 'route.operations_diagnostics',
          capability: 'operations:read'
        }
      },
      {
        name: 'operations_overview',
        path: '/operations/overview',
        component: 'view.operations_overview',
        meta: {
          title: 'operations_overview',
          i18nKey: 'route.operations_overview',
          capability: 'operations:read'
        }
      },
      {
        name: 'operations_traffic',
        path: '/operations/traffic',
        component: 'view.operations_traffic',
        meta: {
          title: 'operations_traffic',
          i18nKey: 'route.operations_traffic',
          capability: 'operations:read'
        }
      },
      {
        name: 'operations_usage-logs',
        path: '/operations/usage-logs',
        component: 'view.operations_usage-logs',
        meta: {
          title: 'operations_usage-logs',
          i18nKey: 'route.operations_usage-logs',
          capability: 'operations:read'
        }
      }
    ]
  },
  {
    name: 'pets',
    path: '/pets',
    component: 'layout.base$view.pets',
    meta: {
      title: 'pets',
      i18nKey: 'route.pets',
      capability: 'content:pets:read',
      icon: 'mdi:cat',
      order: 15
    }
  },
  {
    name: 'plugins',
    path: '/plugins',
    component: 'layout.base$view.plugins',
    meta: {
      title: 'plugins',
      i18nKey: 'route.plugins',
      capability: 'content:plugins:read',
      icon: 'mdi:power-plug-outline',
      order: 13
    }
  },
  {
    name: 'publishing',
    path: '/publishing',
    component: 'layout.base$view.publishing',
    meta: {
      title: 'publishing',
      i18nKey: 'route.publishing',
      capability: 'content:publish:read',
      icon: 'mdi:rocket-launch-outline',
      order: 16
    }
  },
  {
    name: 'runtime',
    path: '/runtime',
    component: 'layout.base',
    meta: {
      title: 'runtime',
      i18nKey: 'route.runtime',
      capability: 'runtime:read',
      icon: 'mdi:server-outline',
      order: 60
    },
    children: [
      {
        name: 'runtime_commands',
        path: '/runtime/commands',
        component: 'view.runtime_commands',
        meta: {
          title: 'runtime_commands',
          i18nKey: 'route.runtime_commands',
          capability: 'runtime:read'
        }
      },
      {
        name: 'runtime_events',
        path: '/runtime/events',
        component: 'view.runtime_events',
        meta: {
          title: 'runtime_events',
          i18nKey: 'route.runtime_events',
          capability: 'runtime:read'
        }
      },
      {
        name: 'runtime_instances',
        path: '/runtime/instances',
        component: 'view.runtime_instances',
        meta: {
          title: 'runtime_instances',
          i18nKey: 'route.runtime_instances',
          capability: 'runtime:read'
        }
      },
      {
        name: 'runtime_operations',
        path: '/runtime/operations',
        component: 'view.runtime_operations',
        meta: {
          title: 'runtime_operations',
          i18nKey: 'route.runtime_operations',
          capability: 'runtime:read'
        }
      },
      {
        name: 'runtime_releases',
        path: '/runtime/releases',
        component: 'view.runtime_releases',
        meta: {
          title: 'runtime_releases',
          i18nKey: 'route.runtime_releases',
          capability: 'runtime:read'
        }
      }
    ]
  },
  {
    name: 'security',
    path: '/security',
    component: 'layout.base',
    meta: {
      title: 'security',
      i18nKey: 'route.security',
      capability: 'auth:session',
      icon: 'mdi:shield-lock-outline',
      order: 50
    },
    children: [
      {
        name: 'security_account',
        path: '/security/account',
        component: 'view.security_account',
        meta: {
          title: 'security_account',
          i18nKey: 'route.security_account',
          capability: 'auth:session'
        }
      },
      {
        name: 'security_risk',
        path: '/security/risk',
        component: 'view.security_risk',
        meta: {
          title: 'security_risk',
          i18nKey: 'route.security_risk',
          capability: 'operations:read'
        }
      }
    ]
  },
  {
    name: 'skills',
    path: '/skills',
    component: 'layout.base$view.skills',
    meta: {
      title: 'skills',
      i18nKey: 'route.skills',
      capability: 'content:skills:read',
      icon: 'mdi:puzzle-star-outline',
      order: 12
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      capability: 'system:read',
      icon: 'mdi:cog-outline',
      order: 80
    },
    children: [
      {
        name: 'system_data',
        path: '/system/data',
        component: 'view.system_data',
        meta: {
          title: 'system_data',
          i18nKey: 'route.system_data',
          capability: 'system:read'
        }
      },
      {
        name: 'system_settings',
        path: '/system/settings',
        component: 'view.system_settings',
        meta: {
          title: 'system_settings',
          i18nKey: 'route.system_settings',
          capability: 'system:read'
        }
      }
    ]
  },
  {
    name: 'users',
    path: '/users',
    component: 'layout.base$view.users',
    meta: {
      title: 'users',
      i18nKey: 'route.users',
      capability: 'users:read',
      icon: 'mdi:account-group-outline',
      order: 20
    }
  }
];
