/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type ElegantConstRoute = import('@elegant-router/vue').ElegantConstRoute;

  /**
   * route layout
   */
  export type RouteLayout = "base" | "blank";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "admins": "/admins";
    "agents": "/agents";
    "ai-resources": "/ai-resources";
    "ai-resources_accounts": "/ai-resources/accounts";
    "ai-resources_channels": "/ai-resources/channels";
    "ai-resources_groups": "/ai-resources/groups";
    "ai-resources_monitoring": "/ai-resources/monitoring";
    "ai-resources_network": "/ai-resources/network";
    "ai-resources_proxies": "/ai-resources/proxies";
    "announcements": "/announcements";
    "audit": "/audit";
    "billing": "/billing";
    "billing_orders": "/billing/orders";
    "billing_overview": "/billing/overview";
    "billing_plans": "/billing/plans";
    "billing_providers": "/billing/providers";
    "billing_subscriptions": "/billing/subscriptions";
    "categories": "/categories";
    "home": "/home";
    "iframe-page": "/iframe-page/:url";
    "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?";
    "marketing": "/marketing";
    "media": "/media";
    "operations": "/operations";
    "operations_alerts": "/operations/alerts";
    "operations_diagnostics": "/operations/diagnostics";
    "operations_overview": "/operations/overview";
    "operations_traffic": "/operations/traffic";
    "operations_usage-logs": "/operations/usage-logs";
    "pets": "/pets";
    "plugins": "/plugins";
    "publishing": "/publishing";
    "runtime": "/runtime";
    "runtime_commands": "/runtime/commands";
    "runtime_events": "/runtime/events";
    "runtime_instances": "/runtime/instances";
    "runtime_operations": "/runtime/operations";
    "runtime_releases": "/runtime/releases";
    "security": "/security";
    "security_account": "/security/account";
    "security_risk": "/security/risk";
    "skills": "/skills";
    "system": "/system";
    "system_data": "/system/data";
    "system_settings": "/system/settings";
    "users": "/users";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "admins"
    | "agents"
    | "ai-resources"
    | "announcements"
    | "audit"
    | "billing"
    | "categories"
    | "home"
    | "iframe-page"
    | "login"
    | "marketing"
    | "media"
    | "operations"
    | "pets"
    | "plugins"
    | "publishing"
    | "runtime"
    | "security"
    | "skills"
    | "system"
    | "users"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "login"
    | "admins"
    | "agents"
    | "ai-resources_accounts"
    | "ai-resources_channels"
    | "ai-resources_groups"
    | "ai-resources_monitoring"
    | "ai-resources_network"
    | "ai-resources_proxies"
    | "announcements"
    | "audit"
    | "billing_orders"
    | "billing_overview"
    | "billing_plans"
    | "billing_providers"
    | "billing_subscriptions"
    | "categories"
    | "home"
    | "marketing"
    | "media"
    | "operations_alerts"
    | "operations_diagnostics"
    | "operations_overview"
    | "operations_traffic"
    | "operations_usage-logs"
    | "pets"
    | "plugins"
    | "publishing"
    | "runtime_commands"
    | "runtime_events"
    | "runtime_instances"
    | "runtime_operations"
    | "runtime_releases"
    | "security_account"
    | "security_risk"
    | "skills"
    | "system_data"
    | "system_settings"
    | "users"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the single level route key
   */
  export type SingleLevelRouteKey = FirstLevelRouteKey & LastLevelRouteKey;

  /**
   * the custom single level route key
   */
  export type CustomSingleLevelRouteKey = CustomFirstLevelRouteKey & CustomLastLevelRouteKey;

  /**
   * the first level route key, but not the single level
  */
  export type FirstLevelRouteNotSingleKey = Exclude<FirstLevelRouteKey, SingleLevelRouteKey>;

  /**
   * the custom first level route key, but not the single level
   */
  export type CustomFirstLevelRouteNotSingleKey = Exclude<CustomFirstLevelRouteKey, CustomSingleLevelRouteKey>;

  /**
   * the center level route key
   */
  export type CenterLevelRouteKey = Exclude<GeneratedRouteKey, FirstLevelRouteKey | LastLevelRouteKey>;

  /**
   * the custom center level route key
   */
  export type CustomCenterLevelRouteKey = Exclude<CustomRouteKey, CustomFirstLevelRouteKey | CustomLastLevelRouteKey>;

  /**
   * the center level route key
   */
  type GetChildRouteKey<K extends RouteKey, T extends RouteKey = RouteKey> = T extends `${K}_${infer R}`
    ? R extends `${string}_${string}`
      ? never
      : T
    : never;

  /**
   * the single level route
   */
  type SingleLevelRoute<K extends SingleLevelRouteKey = SingleLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}$view.${K}`;
      }
    : never;

  /**
   * the last level route
   */
  type LastLevelRoute<K extends GeneratedRouteKey> = K extends LastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `view.${K}`;
      }
    : never;
  
  /**
   * the center level route
   */
  type CenterLevelRoute<K extends GeneratedRouteKey> = K extends CenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the multi level route
   */
  type MultiLevelRoute<K extends FirstLevelRouteNotSingleKey = FirstLevelRouteNotSingleKey> = K extends string
    ? ElegantConstRoute & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}`;
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;
  
  /**
   * the custom first level route
   */
  type CustomSingleLevelRoute<K extends CustomFirstLevelRouteKey = CustomFirstLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `layout.${RouteLayout}$view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom last level route
   */
  type CustomLastLevelRoute<K extends CustomRouteKey> = K extends CustomLastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom center level route
   */
  type CustomCenterLevelRoute<K extends CustomRouteKey> = K extends CustomCenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom multi level route
   */
  type CustomMultiLevelRoute<K extends CustomFirstLevelRouteNotSingleKey = CustomFirstLevelRouteNotSingleKey> =
    K extends string
      ? ElegantConstRoute & {
          name: K;
          path: RouteMap[K];
          component: `layout.${RouteLayout}`;
          children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
        }
      : never;

  /**
   * the custom route
   */
  type CustomRoute = CustomSingleLevelRoute | CustomMultiLevelRoute;

  /**
   * the generated route
   */
  type GeneratedRoute = SingleLevelRoute | MultiLevelRoute;

  /**
   * the elegant route
   */
  type ElegantRoute = GeneratedRoute | CustomRoute;
}
