/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    media: Media;
    'expert-categories': ExpertCategory;
    'skill-catalog': SkillCatalog;
    'agent-templates': AgentTemplate;
    'plugin-catalog': PluginCatalog;
    'pet-assets': PetAsset;
    'integration-settings': IntegrationSetting;
    'audit-logs': AuditLog;
    'cloud-operation-receipts': CloudOperationReceipt;
    'content-delivery-links': ContentDeliveryLink;
    'official-rollback-requests': OfficialRollbackRequest;
    'runtime-instances': RuntimeInstance;
    'runtime-releases': RuntimeRelease;
    'runtime-commands': RuntimeCommand;
    'runtime-events': RuntimeEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'expert-categories': ExpertCategoriesSelect<false> | ExpertCategoriesSelect<true>;
    'skill-catalog': SkillCatalogSelect<false> | SkillCatalogSelect<true>;
    'agent-templates': AgentTemplatesSelect<false> | AgentTemplatesSelect<true>;
    'plugin-catalog': PluginCatalogSelect<false> | PluginCatalogSelect<true>;
    'pet-assets': PetAssetsSelect<false> | PetAssetsSelect<true>;
    'integration-settings': IntegrationSettingsSelect<false> | IntegrationSettingsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'cloud-operation-receipts': CloudOperationReceiptsSelect<false> | CloudOperationReceiptsSelect<true>;
    'content-delivery-links': ContentDeliveryLinksSelect<false> | ContentDeliveryLinksSelect<true>;
    'official-rollback-requests': OfficialRollbackRequestsSelect<false> | OfficialRollbackRequestsSelect<true>;
    'runtime-instances': RuntimeInstancesSelect<false> | RuntimeInstancesSelect<true>;
    'runtime-releases': RuntimeReleasesSelect<false> | RuntimeReleasesSelect<true>;
    'runtime-commands': RuntimeCommandsSelect<false> | RuntimeCommandsSelect<true>;
    'runtime-events': RuntimeEventsSelect<false> | RuntimeEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  displayName: string;
  role: 'super_admin' | 'operations_admin' | 'publisher' | 'finance_admin' | 'auditor';
  active: boolean;
  /**
   * 调用 aera-cloud 内部管理 API 时使用的稳定 UUID 身份，自动生成。
   */
  cloudActorId?: string | null;
  totpSecret?: string | null;
  /**
   * 高危操作二次验证（TOTP）的绑定时间，未绑定时为空。
   */
  totpEnabledAt?: string | null;
  stepUpVerifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  attribution?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expert-categories".
 */
export interface ExpertCategory {
  id: number;
  key: string;
  name: string;
  englishName?: string | null;
  description?: string | null;
  sortOrder: number;
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-catalog".
 */
export interface SkillCatalog {
  id: number;
  key: string;
  name: string;
  description?: string | null;
  runtimeSkillId: string;
  minimumRuntimeVersion?: string | null;
  active: boolean;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-templates".
 */
export interface AgentTemplate {
  id: number;
  templateKey: string;
  name: string;
  englishName?: string | null;
  avatar: number | Media;
  category: number | ExpertCategory;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  introduction: string;
  rolePrompt: string;
  skills?: (number | SkillCatalog)[] | null;
  releaseVersion?: number | null;
  releaseNotes?: string | null;
  minimumStudioVersion?: string | null;
  minimumRuntimeVersion?: string | null;
  publishedFingerprint?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-catalog".
 */
export interface PluginCatalog {
  id: number;
  name: string;
  slug: string;
  version: string;
  summary: string;
  installKind: 'standalone_plugin' | 'pip_entry_point' | 'runtime_bundled';
  artifactURL: string;
  checksum: string;
  compatibility?: {
    minimumRuntimeVersion?: string | null;
    maximumRuntimeVersion?: string | null;
    platforms?: ('macos' | 'windows' | 'linux')[] | null;
  };
  riskLevel: 'low' | 'medium' | 'high';
  enabled: boolean;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pet-assets".
 */
export interface PetAsset {
  id: number;
  name: string;
  slug: string;
  version: string;
  manifest?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  spriteMedia?: (number | null) | Media;
  previewMedia?: (number | null) | Media;
  compatibility?: {
    minimumStudioVersion?: string | null;
    minimumRuntimeVersion?: string | null;
  };
  enabled: boolean;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration-settings".
 */
export interface IntegrationSetting {
  id: number;
  service: 'agentera_api';
  enabled: boolean;
  healthStatus: 'healthy' | 'unavailable' | 'not_configured';
  lastCheckedAt: string;
  lastErrorCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  actorId: string;
  actorEmail?: string | null;
  actorRole: 'super_admin' | 'operations_admin' | 'publisher' | 'finance_admin' | 'auditor';
  capability:
    | 'auth:session'
    | 'dashboard:read'
    | 'admins:read'
    | 'admins:write'
    | 'content:agents:read'
    | 'content:agents:write'
    | 'content:agents:publish'
    | 'content:categories:read'
    | 'content:categories:write'
    | 'content:skills:read'
    | 'content:skills:write'
    | 'content:skills:publish'
    | 'content:plugins:read'
    | 'content:plugins:write'
    | 'content:plugins:publish'
    | 'content:media:read'
    | 'content:media:write'
    | 'content:pets:read'
    | 'content:pets:write'
    | 'content:pets:publish'
    | 'content:publish:read'
    | 'content:publish:execute'
    | 'users:read'
    | 'users:write'
    | 'users:balance:update'
    | 'ai-resources:read'
    | 'ai-resources:write'
    | 'billing:read'
    | 'billing:write'
    | 'billing:order:refund'
    | 'operations:read'
    | 'operations:write'
    | 'runtime:read'
    | 'runtime:command:create'
    | 'tenants:read'
    | 'tenants:write'
    | 'audit:read'
    | 'system:read'
    | 'system:write'
    | 'system:backup:restore'
    | 'cloud:users:read'
    | 'cloud:users:write'
    | 'cloud:devices:write'
    | 'cloud:sessions:write'
    | 'official-agents:read'
    | 'official-agents:draft:write'
    | 'official-agents:review:write'
    | 'official-agents:release:write'
    | 'official-agents:rollback:write';
  action: string;
  resourceType: string;
  resourceId?: string | null;
  resourceName?: string | null;
  requestId: string;
  operationId?: string | null;
  upstreamRequestId?: string | null;
  outcome: 'succeeded' | 'failed';
  errorCode?: string | null;
  ip?: string | null;
  userAgent?: string | null;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  occurredAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cloud-operation-receipts".
 */
export interface CloudOperationReceipt {
  id: number;
  operationId: string;
  operationKey: string;
  requestId: string;
  actorAdminId: string;
  actorRole: string;
  localActorId: string;
  localActorRole: string;
  capability: string;
  request:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rollbackRequestId?: string | null;
  status: 'pending' | 'reconciling' | 'succeeded' | 'failed' | 'conflict';
  administrativeRevision?: number | null;
  cloudStatus?: ('queued' | 'executing' | 'succeeded' | 'failed' | 'conflict') | null;
  cloudUpdatedAt?: string | null;
  errorCode?: string | null;
  lastErrorCode?: string | null;
  definitiveFailure: boolean;
  attemptCount: number;
  lastAttemptAt?: string | null;
  nextAttemptAt?: string | null;
  leaseOwner?: string | null;
  leaseExpiresAt?: string | null;
  auditCompletedAt?: string | null;
  rollbackCompletedAt?: string | null;
  upstreamRequestId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-delivery-links".
 */
export interface ContentDeliveryLink {
  id: number;
  resourceType: 'agent' | 'category' | 'skill' | 'plugin';
  payloadDocumentId: string;
  stableKey: string;
  cloudDefinitionId?: string | null;
  cloudDraftId?: string | null;
  cloudSubmissionId?: string | null;
  cloudVersionId?: string | null;
  cloudReleaseId?: string | null;
  payloadRevision?: number | null;
  contentDigest?: string | null;
  runtimeManifestSha256?: string | null;
  syncStatus:
    | 'local_only'
    | 'draft_synced'
    | 'validation_failed'
    | 'submitted'
    | 'approved'
    | 'released'
    | 'desktop_verified'
    | 'failed';
  lastOperationId?: string | null;
  lastRequestId?: string | null;
  lastErrorCode?: string | null;
  lastErrorSummary?: string | null;
  desktopVerification?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "official-rollback-requests".
 */
export interface OfficialRollbackRequest {
  id: number;
  approvalId?: string | null;
  releaseId: string;
  targetVersionId: string;
  targetReleaseRevisionId: string;
  expectedRevision: number;
  reasonCode: string;
  ticketReference?: string | null;
  status: 'requested' | 'approved' | 'rejected' | 'executed' | 'cancelled';
  requestedBy: number | Admin;
  requestedByActorId: string;
  decidedBy?: (number | null) | Admin;
  decidedByActorId?: string | null;
  decidedAt?: string | null;
  decisionNote?: string | null;
  executedAt?: string | null;
  operationId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtime-instances".
 */
export interface RuntimeInstance {
  id: number;
  name: string;
  instanceType: 'runtime' | 'studio' | 'desktop';
  tenantId?: string | null;
  status: 'pending' | 'offline' | 'online' | 'disabled';
  deviceIdHash: string;
  deviceSecretHash?: string | null;
  enrollmentCodeHash?: string | null;
  enrollmentExpiresAt?: string | null;
  version?: string | null;
  os?: string | null;
  arch?: string | null;
  capabilities?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lastHeartbeatAt?: string | null;
  healthSummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  channels?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  resources?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtime-releases".
 */
export interface RuntimeRelease {
  id: number;
  product: 'runtime' | 'studio' | 'desktop';
  version: string;
  channel: 'stable' | 'beta' | 'nightly';
  minimumVersion?: string | null;
  artifactURL: string;
  checksum: string;
  publishedAt?: string | null;
  status: 'draft' | 'published' | 'retired';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtime-commands".
 */
export interface RuntimeCommand {
  id: number;
  instance: number | RuntimeInstance;
  type: 'health_check';
  requiredCapability: string;
  idempotencyKey: string;
  commandKey: string;
  state: 'queued' | 'claimed' | 'running' | 'succeeded' | 'failed' | 'expired';
  expiresAt?: string | null;
  claimedAt?: string | null;
  startedAt?: string | null;
  completedAt?: string | null;
  resultCode?: string | null;
  resultSummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  createdBy?: (number | null) | Admin;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtime-events".
 */
export interface RuntimeEvent {
  id: number;
  instance: number | RuntimeInstance;
  kind: string;
  severity: 'info' | 'warning' | 'error';
  code?: string | null;
  summary: string;
  occurredAt: string;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'expert-categories';
        value: number | ExpertCategory;
      } | null)
    | ({
        relationTo: 'skill-catalog';
        value: number | SkillCatalog;
      } | null)
    | ({
        relationTo: 'agent-templates';
        value: number | AgentTemplate;
      } | null)
    | ({
        relationTo: 'plugin-catalog';
        value: number | PluginCatalog;
      } | null)
    | ({
        relationTo: 'pet-assets';
        value: number | PetAsset;
      } | null)
    | ({
        relationTo: 'integration-settings';
        value: number | IntegrationSetting;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'cloud-operation-receipts';
        value: number | CloudOperationReceipt;
      } | null)
    | ({
        relationTo: 'content-delivery-links';
        value: number | ContentDeliveryLink;
      } | null)
    | ({
        relationTo: 'official-rollback-requests';
        value: number | OfficialRollbackRequest;
      } | null)
    | ({
        relationTo: 'runtime-instances';
        value: number | RuntimeInstance;
      } | null)
    | ({
        relationTo: 'runtime-releases';
        value: number | RuntimeRelease;
      } | null)
    | ({
        relationTo: 'runtime-commands';
        value: number | RuntimeCommand;
      } | null)
    | ({
        relationTo: 'runtime-events';
        value: number | RuntimeEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  displayName?: T;
  role?: T;
  active?: T;
  cloudActorId?: T;
  totpSecret?: T;
  totpEnabledAt?: T;
  stepUpVerifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  attribution?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expert-categories_select".
 */
export interface ExpertCategoriesSelect<T extends boolean = true> {
  key?: T;
  name?: T;
  englishName?: T;
  description?: T;
  sortOrder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-catalog_select".
 */
export interface SkillCatalogSelect<T extends boolean = true> {
  key?: T;
  name?: T;
  description?: T;
  runtimeSkillId?: T;
  minimumRuntimeVersion?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-templates_select".
 */
export interface AgentTemplatesSelect<T extends boolean = true> {
  templateKey?: T;
  name?: T;
  englishName?: T;
  avatar?: T;
  category?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  introduction?: T;
  rolePrompt?: T;
  skills?: T;
  releaseVersion?: T;
  releaseNotes?: T;
  minimumStudioVersion?: T;
  minimumRuntimeVersion?: T;
  publishedFingerprint?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-catalog_select".
 */
export interface PluginCatalogSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  version?: T;
  summary?: T;
  installKind?: T;
  artifactURL?: T;
  checksum?: T;
  compatibility?:
    | T
    | {
        minimumRuntimeVersion?: T;
        maximumRuntimeVersion?: T;
        platforms?: T;
      };
  riskLevel?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pet-assets_select".
 */
export interface PetAssetsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  version?: T;
  manifest?: T;
  spriteMedia?: T;
  previewMedia?: T;
  compatibility?:
    | T
    | {
        minimumStudioVersion?: T;
        minimumRuntimeVersion?: T;
      };
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration-settings_select".
 */
export interface IntegrationSettingsSelect<T extends boolean = true> {
  service?: T;
  enabled?: T;
  healthStatus?: T;
  lastCheckedAt?: T;
  lastErrorCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  actorId?: T;
  actorEmail?: T;
  actorRole?: T;
  capability?: T;
  action?: T;
  resourceType?: T;
  resourceId?: T;
  resourceName?: T;
  requestId?: T;
  operationId?: T;
  upstreamRequestId?: T;
  outcome?: T;
  errorCode?: T;
  ip?: T;
  userAgent?: T;
  before?: T;
  after?: T;
  occurredAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cloud-operation-receipts_select".
 */
export interface CloudOperationReceiptsSelect<T extends boolean = true> {
  operationId?: T;
  operationKey?: T;
  requestId?: T;
  actorAdminId?: T;
  actorRole?: T;
  localActorId?: T;
  localActorRole?: T;
  capability?: T;
  request?: T;
  rollbackRequestId?: T;
  status?: T;
  administrativeRevision?: T;
  cloudStatus?: T;
  cloudUpdatedAt?: T;
  errorCode?: T;
  lastErrorCode?: T;
  definitiveFailure?: T;
  attemptCount?: T;
  lastAttemptAt?: T;
  nextAttemptAt?: T;
  leaseOwner?: T;
  leaseExpiresAt?: T;
  auditCompletedAt?: T;
  rollbackCompletedAt?: T;
  upstreamRequestId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-delivery-links_select".
 */
export interface ContentDeliveryLinksSelect<T extends boolean = true> {
  resourceType?: T;
  payloadDocumentId?: T;
  stableKey?: T;
  cloudDefinitionId?: T;
  cloudDraftId?: T;
  cloudSubmissionId?: T;
  cloudVersionId?: T;
  cloudReleaseId?: T;
  payloadRevision?: T;
  contentDigest?: T;
  runtimeManifestSha256?: T;
  syncStatus?: T;
  lastOperationId?: T;
  lastRequestId?: T;
  lastErrorCode?: T;
  lastErrorSummary?: T;
  desktopVerification?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "official-rollback-requests_select".
 */
export interface OfficialRollbackRequestsSelect<T extends boolean = true> {
  approvalId?: T;
  releaseId?: T;
  targetVersionId?: T;
  targetReleaseRevisionId?: T;
  expectedRevision?: T;
  reasonCode?: T;
  ticketReference?: T;
  status?: T;
  requestedBy?: T;
  requestedByActorId?: T;
  decidedBy?: T;
  decidedByActorId?: T;
  decidedAt?: T;
  decisionNote?: T;
  executedAt?: T;
  operationId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtime-instances_select".
 */
export interface RuntimeInstancesSelect<T extends boolean = true> {
  name?: T;
  instanceType?: T;
  tenantId?: T;
  status?: T;
  deviceIdHash?: T;
  deviceSecretHash?: T;
  enrollmentCodeHash?: T;
  enrollmentExpiresAt?: T;
  version?: T;
  os?: T;
  arch?: T;
  capabilities?: T;
  lastHeartbeatAt?: T;
  healthSummary?: T;
  channels?: T;
  resources?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtime-releases_select".
 */
export interface RuntimeReleasesSelect<T extends boolean = true> {
  product?: T;
  version?: T;
  channel?: T;
  minimumVersion?: T;
  artifactURL?: T;
  checksum?: T;
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtime-commands_select".
 */
export interface RuntimeCommandsSelect<T extends boolean = true> {
  instance?: T;
  type?: T;
  requiredCapability?: T;
  idempotencyKey?: T;
  commandKey?: T;
  state?: T;
  expiresAt?: T;
  claimedAt?: T;
  startedAt?: T;
  completedAt?: T;
  resultCode?: T;
  resultSummary?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtime-events_select".
 */
export interface RuntimeEventsSelect<T extends boolean = true> {
  instance?: T;
  kind?: T;
  severity?: T;
  code?: T;
  summary?: T;
  occurredAt?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}